### ISSUE TITLE
Metrics like Fully Loaded and Visually Complete are unnecessarily noisy

### ISSUE THREAD

**Issue by hansede** [SpeedCurve-Metrics/SpeedCurve#187] opened 2018-04-09 22:39 UTC
Metrics like Fully Loaded and Visually Complete are unnecessarily noisy because the SpeedIndex is used as the median instead of the individual metric (Fully Loaded, Visually Complete, etc.)

Take this spike in Fully Loaded time as an example:

![screen shot 2018-04-09 at 3 26 48 pm](https://user-images.githubusercontent.com/728164/38526291-80ecfb2a-3c0a-11e8-9578-362ef6d34f64.png)

This value comes from an outlier of the 9 measurements that were taken by WebPageTest:

![screen shot 2018-04-09 at 3 28 13 pm](https://user-images.githubusercontent.com/728164/38526331-b200a2d4-3c0a-11e8-840d-0df60655fdb7.png)

The outlier was used as the data point in spite of the median being selected as the stat for the chart:

![screen shot 2018-04-09 at 3 29 57 pm](https://user-images.githubusercontent.com/728164/38526369-e7c811a4-3c0a-11e8-8b4b-4f836035cabe.png)

This is because SpeedCurve is importing all metrics from the single sample that had the median SpeedIndex. This allows other metrics like Fully Loaded to use a value that is not the median for that individual metric, and in this case was the worst possible outlier. Given that metrics like Fully Loaded and Visually Complete are only correlated to, but not a function of SpeedIndex, the data for these metrics is very noisy.

WebPageTest generates medians for each individual metric that could be imported into SpeedCurve's database to generate charts that are far less noisy. Sorting on individual metrics can be done by passing the `medianMetric` URL param when fetching from WPT's API. For example:

https://wpt1.speedcurve.com/jsonResult.php?test=180323_RE_87b89b191fb9148561a2f05eda91964b&medianMetric=FullyLoaded

Currently the data for many metrics is too noisy for alerting on percent change to be viable. Please fix this issue by importing the individual medians for each metric.

**Comment by MickeyKay** [comment] 2018-04-10 00:43
This is a great suggestion. 👍

**Comment by hansede** [comment] 2018-04-10 23:16
I plotted part of the Fully Loaded chart I pasted above, starting at the `Faster test agents` label. That part is plotted in blue (using SpeedIndex as the median metric), while the actual median of the individual Fully Loaded metric is plotted in red.

![screen shot 2018-04-10 at 4 15 31 pm](https://user-images.githubusercontent.com/728164/38588392-72c74534-3cda-11e8-825c-1a1c1651d6f5.png)

The blue chart (SpeedIndex as median) has the following characteristics:
Standard deviation: 4.55s
Min: 2.96s
Max: 37.41s

The red chart (Fully Loaded as median) has the following characteristics:
Standard deviation: 0.40s
Min: 3.18s
Max: 5.42s

This demonstrates the value of using the individual metrics as their own medians. The standard deviation could be clamped down even tighter by taking more measurements for each data point (I used 9 measurements per point).

**Comment by josephwynn-sc** [comment] 2018-04-10 23:28
@hansede this is awesome, thanks!

**Comment by josephwynn-sc** [comment] 2018-04-12 03:39
The SpeedCurve team discussed this for a while earlier today.

Loading a modern web page is a complex process, and almost all of the time it is non-deterministic. There will always be variability the process of loading a page: the routes that packets take along the network, the availability of system resources on the server(s) and client, etc. Most of this variability is small enough that you don't notice it plotted in a time series. Sometimes there is much more variability than usual - maybe the ad broker couldn't find a bidder and made a huge number of network requests. Maybe the client's CPU was busy doing something else. Regardless of the reason, these page loads are what I would call true outliers. A reliable way to ensure that these outliers are not used as the final test result is to use the median test run. In our experience, using SpeedIndex as the metric to determine the median test run has given relatively consistent results.

The crux of this issue is that the example charts contain more outliers than you would expect, and the goal is to have flat charts, i.e. to hide the variability. However, the variability in these charts is not artificial; it is the result of genuine variability in the way that the page loads. Rather asking how to have flatter charts, we would encourage SpeedCurve users to understand that this variability is affecting real users, and to ask how to improve their pages to reduce the variability.

In saying that, we recognise that SpeedIndex is not always the best metric to use to determine the median test run. We're going to address this by giving you the ability to change the metric used to pick the median test run (I don't have an ETA for this right now, sorry). This setting will likely be at the account level and will not be applied retroactively.

We're not going to enable the median metric to change on a per-metric or a per-chart basis, though. The simple answer for why we won't do this is that doing so would render the charts statistically meaningless. Taking the median test run is a form of statistical sampling, and sampling is only valid if it is done before the observations are made. To draw an analogy (albeit a painful one - sorry!), imagine a page load as a survey, and each metric as a single question on the survey. Re-picking the median for each chart/metric would be like asking each question to an entirely different population sample. The questions in isolation would all have valid answers, but you could not form any valid relationships between the questions because they were all answered by different samples. At this point the survey as a whole is meaningless. To relate that back to page load metrics: because the data for each metric would be coming from an entirely different dataset, you wouldn't be able to correlate any of the metrics. This is a massive hindrance when you're trying to get something meaningful from your data, for example determining the relationship between the number/size of blocking assets and the start render time.

The final thing I'll say is that in the meantime you could experiment with reducing the number of checks per test and increasing the number tests per day. For example rather than running 9 checks once per day, run 3 checks 3 times per day.

**Comment by hansede** [comment] 2018-04-12 18:12
I would suggest that you are introducing a different form of sampling bias by selecting all non-SpeedIndex metrics from a single sample. Analogy time:

Suppose we were to chart the median height of all humans on a daily basis. The chart would be a steady line at 5.4ft, with an almost non-existent standard deviation, but the individual person with the median height would probably be a different person every day. Now let's suppose we were to select the median-heighted person each day and chart the weight of that person. Because we are choosing a different individual each day, the weight chart would be extremely noisy and have a large standard deviation, in spite of height and weight being correlated.

SpeedIndex is correlated to Fully Loaded time, but we are taking the median of a distribution of SpeedIndex and not the median of a distribution of Fully Loaded times. Fully Loaded time will therefore be very noisy, as demonstrated. Knowing that the individual Fully Loaded time selected for each test run came from the same individual sample as the median SpeedIndex is not useful to me, I want to know the median Fully Loaded time of the population.

What I am looking to get out of these charts:
- See if my metric (Visually Complete, Fully Loaded, etc.) is on average getting better or worse over time
- See the standard deviation for each test run to know how much variability exists
- Alert when the average or standard deviation changes significantly

For some metrics there is just too much noise right now (or lack of data in the case of standard deviation) to accomplish these goals. Alerting especially is impossible because of the large amount of noise.

**Comment by timmfin** [comment] 2018-04-13 01:05
While I by no means consider myself an expert statistician, I agree with @hansede. That is likely because to me, the primary thing I'm trying to get out of SpeedCurve is our performance trend over time (weeks and months more important than days). Personally, I'm very willing to sacrifice some (or maybe a lot?) of individual datapoint precision/meaning in order to have a more discernible (and more alertable/automation friendly) trend line.

Maybe a better solution to that is having _additional_ charts that provide a rolling average or some other rollup/smoothing mechanism (as suggested [here](https://github.com/SpeedCurve-Metrics/SpeedCurve/issues/188)). But nonetheless, many of our current needs are not being met very well by these (seemingly excessively?) noisy charts.

/cc @Phoenixmatrix

**Comment by josephwynn-sc** [comment] 2018-04-13 04:13
@hansede your analogy is perfect for RUM! There are so many variations in the human population that it wouldn't make sense to infer the median weight of the population by looking at the person with the median height. For exactly this reason, our RUM product (SpeedCurve LUX) aggregates metrics over the entire dataset for each metric rather than doing any sampling.

Synthetic is different though, and the analogy doesn't quite stack up. With synthetic performance testing, we have full control over a great deal of the variables, which gives us confidence that the testing process itself is consistent and that any variability is almost always in the page being tested.

Let me rewind for a second. Imagine you ran one check per test instead of nine (NB: SpeedCurve doesn't let you run fewer than three checks). There would be no "median check", but you would _still have variability in your charts_ because every 1 in N page loads would still have a high fully loaded time. The only difference is that the variability would be spread out over a longer period of time. In this scenario, there are are two likely causes for the variability:

1. The page itself does not load consistently, in which case the variability has identified a real-world performance issue (albeit a sporadic/intermittent one). We can fix the variability by fixing the performance issue on the page.
2. There is a problem with the testing process, like the test agent being slow. Whenever there's a problem with the testing process, then it's _extremely likely_ that all of the metrics will be out of whack -- not just one metric. To bring us full circle, this is the reason we run multiple checks. We pick the median check based on SpeedIndex because if there is a problem with the testing process, it's _extremely likely_ that SpeedIndex will also be affected by this problem, and the problem check will be discarded.

@hansede - As I mentioned in our private conversation, fully loaded is an inherently noisy metric and I advise against using it for any alerting. Any page of non-trivial complexity will have a noisy fully loaded time. Heck, even [my blog](https://wildlyinaccurate.com/) has a noisy fully loaded time and it's about as simple as a modern web page gets:

![screenshot from 2018-04-13 16-00-23](https://user-images.githubusercontent.com/31634862/38716283-f2d0033c-3f33-11e8-9215-3e729bd1fe1d.png)

I also stand by my original comments about asking yourself how to remove the variability from your pages rather than from your charts. In saying that, I am easily convinced by good data so if you (or @timmfin, or anyone else in this thread) have any examples of other metrics (_not_ fully loaded) being unnecessarily noisy then please send them over to us (you can send them to support@speedcurve.com if you'd rather not post anything publicly) and we can help you dig into why it's noisy.

**Comment by josephwynn-sc** [comment] 2019-02-13 23:00
We're reviewing our public issues as a team and have decided to close this ticket. You can now plot a linear regression trend line on all of your charts, which should help to smooth out the noise. We would also recommend using [WebPageTest Scripting](https://support.speedcurve.com/using-synthetic/adding-webpagetest-scripts-to-urls) to block the resources that are causing these spikes.

**Closed by josephwynn-sc** 2019-02-13 23:00 UTC
